version: '2'
services:
  php:
    restart: always
    image: ccr.ccs.tencentyun.com/qyy-base/qyy-php:1.0.0
    container_name: game
    volumes:
    - /d/WWW/gamer/game:/home/worker/data/www/game
    - /d/WWW/miniprogram/ld:/home/worker/data/www/ld
    - /d/WWW/gamer/gamer-socket:/home/worker/data/www/gamer-socket
    - /d/WWW/gamer/gamer-worker:/home/worker/data/www/gamer-worker
    - /d/WWW/ibosapi:/home/worker/data/www/ibosapi
    - ./php/php-fpm.ini:/home/worker/php/etc/php-fpm.ini
    - ./php/php-fpm.conf:/home/worker/php/etc/php-fpm.conf
    - ./php/php.d/xdebug.ini:/home/worker/php/etc/php.d/xdebug.ini
    - ./nginx/nginx.conf:/home/worker/nginx/conf/nginx.conf
    - ./game.conf:/home/worker/nginx/conf.d/game.conf
    - ./ld.conf:/home/worker/nginx/conf.d/ld.conf
    - ./game.sh:/etc/my_init.d/game.sh
    ports:
      - "80:80"
    networks:
      - new
    depends_on:
      - redis
      - memcached
      - mysql
    extra_hosts:
      - "wqdapi.cc:192.168.1.9"
      - "ld.cc:192.168.1.9"
  redis:
    restart: always
    image:  registry.cn-hangzhou.aliyuncs.com/qyyteam/redis:1.0.0
    ports:
      - "6379:6379"
    volumes:
      - /d/persistent/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - new 
    container_name: redis
  memcached:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/qyyteam/memcached:1.0.0
    ports:
      - "11211:11211"
    networks:
      - new 
    container_name: memcached
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/qyyteam/mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d:/etc/mysql/conf.d
      - /d/server/MySql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - new 
    container_name: mysql
networks:
    new: